const KEYWORDS =  {
    ATTUNE: 'attune',
    BARRIER: 'barrier',
    BURST: 'burst',
    CANT_BLOCK: 'cant_block',
    CAPTURE: 'capture',
    CHALLENGER: 'challenger',
    DEEP: 'deep',
    DOUBLE_ATTACK: 'double_attack',
    ELUSIVE: 'elusive',
    EPHEMERAL: 'ephemeral',
    FAST: 'fast',
    FEARSOME: 'fearsome',
    FLEETING: 'fleeting',
    FROSTBITE: 'frostbite',
    FURY: 'fury',
    IMMOBILE: 'immobile',
    LAST_BREATH: 'last_breath',
    QUICK_ATTACK: 'quick_attack',
    LIFESTEAL: 'lifesteal',
    OVERWHELM: 'overwhelm',
    REGENERATION: 'regeneration',
    SCOUT: 'scout',
    SILENCE: 'silence',
    SKILL: 'skill',
    SLOW: 'slow',
    SPELLSHIELD: 'spellshield',
    STUN: 'stun',
    TOUGH: 'tough',
    VULNERABLE: 'vulnerable'
}

export default KEYWORDS;